### PR TITLE
Adding ovs patch port 

### PR DESCRIPTION
**Pull request by SharonBX**

### CODE REVIEW

**Review by karthiksundaravel — COMMENTED** [review]
LGTM ! Lets hear Dan's comments

**Review by dsneddon — APPROVED** [review]
Thank you for making the changes to the earlier patchset. This version is much improved in both the flow of the added pending bridge port and the test case that adds the port before the bridge. I appreciate the added effort and the quality of the result.

**Review by dsneddon — APPROVED** [review]
Looks good.

**Comment by SharonBX** [comment]
big credit to @karthiksundaravel  who helped all the way .

**Pull request merged**
