### PR TITLE
Add ovs_extra param for mac table size

### PR DESCRIPTION
**Pull request by vcandapp**
Update ovs_extra to set the MAC table limit
for OvSBridge in nm provider

### CODE REVIEW

**Review by karthiksundaravel — APPROVED** [review]
Thanks

**Comment by vcandapp** [comment]
recheck

**Comment by raukadah** [comment]
recheck ci fixed!

**Comment by vcandapp** [comment]
recheck

**Review by dsneddon — COMMENTED** [review]
This looks good to me provided the recheck works

**Pull request merged**
